### ISSUE TITLE
jwtToken being loaded from localStorage instead of sessionStorage

### ISSUE THREAD

**Issue by bnason** [node-vision/strapi-plugin-entity-relationship-chart#1]
In order for me to get this to work in my Strapi project, I had to modify it to use `sessionStorage` instead of `localStorage` when loading `jwtToken`. Here is the line I modified: https://github.com/node-vision/strapi-plugin-entity-relationship-chart/blob/master/admin/src/containers/HomePage/index.js#L89

I'm running Strapi v3.0.1 (node v12.14.0)

Thanks for the great plugin!

**Comment by romanmandryk** [comment]
That's interesting. I tried on v 3.0.0 and also 3.0.2 and it always stores jwtToken in localStorage. But I will add a fallback to sessionStorage anyway.

**Comment by romanmandryk** [comment]
@bnason, I have published a new version using strapi-plugin-helper which should sort out automatically issues with jwtToken. Please retry with v0.2.0
