### ISSUE TITLE
[BUG] Strapi Build Error

### ISSUE THREAD

**Issue by ssameeraxioned** [node-vision/strapi-plugin-entity-relationship-chart#22]
I'm facing this given below error when package is building by `npm run build`

**Error: Module not found: Error: Can't resolve '@strapi/icons/OneToMany'**

**strapi-plugin-entity-relationship-chart: "^4.1.0"
Strapi: 3.6.10
Node: v14.19.3
NPM: 6.14.17**

**Comment by ralexrdz** [comment]
I'm experiencing the same u_u. Unable to fix it with. yarn add @strapi/icons or yarn add @strapi/design-system

any temporal work around?
