### ISSUE TITLE
Draw relations implemented via components

### ISSUE THREAD

**Issue by jorisw** [node-vision/strapi-plugin-entity-relationship-chart#4]
Hi, 

Great plug-in. Works well on Strapi 3.3.4.

The only thing missing for us is relationship lines between entities that are connected via component arrays. For example, we have a structure like this:

- Parent content type
  - Field "chidren": Component Array
     - 1:1 Relationship field to other 'child' content type

This allows us to fully manage the order of relations. This plug-in doesn't appear to pick up on the nested relationship. Probably doesn't visualize components altogether.

**Comment by stepanjakl** [comment]
Yes, that would be a very useful feature✌️ 

Also, showing the relationships (i.e. one-to-one, one-to-many, many-to-many) would be super helpful.

That would help my team to navigate through the connections very easily without a need for external UML generator software.

**Comment by SalahAdDin** [comment]
Yes, we saw it too:
![image](https://user-images.githubusercontent.com/5034215/123091437-0149d000-d432-11eb-9db3-4cf2e74ed7b4.png)

**Comment by romanmandryk** [comment]
implemented in new version 4.1.0
