### ISSUE TITLE
Doesn't work for all types of relationships

### ISSUE THREAD

**Issue by ch3ckmat3** [node-vision/strapi-plugin-entity-relationship-chart#7]
First of all, great work!

I tested it on latest stable release v3.4.6, works great. I figured that the plugin depends on both entities to have a reference field to draw relationship line, while there are types of relationships between entities where only one side has a reference filed, for example:
If a Product can have one Category, the Product entity will have "product" field, and Category don't need a reference field to Product.

It would be great if the plugin can infer from these types of relationships to properly draw the diagram, and as someone already requested, show the cardinality (or type of relationship) as well.

Also, if possible, the plugin can generate metadata tables/collections and save the states of diagram(s), where one can create a new diagram tab, and choose which entities to show in that diagram (helps to generate documentation by subject), and save this state.

Cheers

**Comment by SalahAdDin** [comment]
Neither all modles, like **UploadFile**:
![image](https://user-images.githubusercontent.com/5034215/123091362-ec6d3c80-d431-11eb-8147-327254033d48.png)

**Comment by ch3ckmat3** [comment]
If the entities metadata with relationships could be exported (using a wizard type flow, to select entities and related options) in a draw.io compatible format, would be wonderful way to document and use the ER diagrams.

The workflow definition can be saved so on any changes in db schema can be exported using the same set of options etc.

**Comment by romanmandryk** [comment]
implemented in new version 4.1.0

**Comment by SalahAdDin** [comment]
> implemented in new version 4.1.0

It is not available for the third version, right?

**Comment by romanmandryk** [comment]
No, only v4 will receive new updates.
